FROM debian:latest
MAINTAINER Christian U. <info@cu-tec.de>
# Installing packages
RUN apt-get update && apt-get upgrade -y
RUN wget http://downloads.free-erp.de/promet-erp-services_PVERSION_amd64-gtk2.deb --level=RANDOMNUMBER && dpkg -i promet-erp-services_PVERSION_amd64-gtk2.deb && rm promet-erp-services_PVERSION_amd64-gtk2.deb
RUN apt-get clean && apt-get autoremove -y

EXPOSE 5901